export enum BaseLegal {	
    CONSENTIMIENTO = 'CONSENTIMIENTO',      
    CONTRATO = 'CONTRATO',
    OBLIGACION_LEGAL = 'OBLIGACION_LEGAL',     
    INTERES_VITAL = 'INTERES_VITAL',        
    INTERES_PUBLICO = 'INTERES_PUBLICO',      
    INTERES_LEGITIMO = 'INTERES_LEGITIMO'
};

export enum MetodoObtencion {
    FORMULARIO_WEB = 'FORMULARIO_WEB',
    CORREO_ELECTRONICO = 'CORREO_ELECTRONICO',
    APP_MOVIL = 'APP_MOVIL',
    DOCUMENTO_FISICO = 'DOCUMENTO_FISICO',
};

export enum EstadoConsent {
    ACTIVO = 'ACTIVO',
    REVOCADO = 'REVOCADO',
    PENDIENTE = 'PENDIENTE',
    RECHAZADO = 'RECHAZADO',
};

export enum Finalidad {
    REGISTRO_AUTENTICACION = 'REGISTRO_AUTENTICACION',
    PRESTACION_SERVICIO = 'PRESTACION_SERVICIO',
    GESTION_PAGOS = 'GESTION_PAGOS',
    SEGURIDAD_PREVENCION_FRAUDE = 'SEGURIDAD_PREVENCION_FRAUDE',
    PUBLICIDAD_PERSONALIZADA = 'PUBLICIDAD_PERSONALIZADA',
    ANALISIS_MEJORA_SERVICIO = 'ANALISIS_MEJORA_SERVICIO',
    PERSONALIZACION_CONTENIDO = 'PERSONALIZACION_CONTENIDO',
    INTEGRACION_TERCEROS = 'INTEGRACION_TERCEROS',
    CUMPLIMIENTO_LEGAL = 'CUMPLIMIENTO_LEGAL',
    GESTION_DERECHOS_USUARIO = 'GESTION_DERECHOS_USUARIO',
    ENVIO_NOTIFICACIONES = 'ENVIO_NOTIFICACIONES',
    GESTION_SOPORTE_TECNICO = 'GESTION_SOPORTE_TECNICO',
  }