export enum BaseLegal {	
    CONSENTIMIENTO = 'CONSENTIMIENTO',      
    CONTRATO = 'CONTRATO',
    OBLIGACION_LEGAL = 'OBLIGACION_LEGAL',     
    INTERES_VITAL = 'INTERES_VITAL',        
    INTERES_PUBLICO = 'INTERES_PUBLICO',      
    INTERES_LEGITIMO = 'INTERES_LEGITIMO'
};

export enum MetodoObtencion {
    FORMULARIO_WEB = 'FORMULARIO_WEB',
    CORREO_ELECTRONICO = 'CORREO_ELECTRONICO',
    APP_MOVIL = 'APP_MOVIL',
    DOCUMENTO_FISICO = 'DOCUMENTO_FISICO',
};

export enum EstadoConsent {
    ACTIVO = 'ACTIVO',
    REVOCADO = 'REVOCADO',
};