export enum TipoSensible {
  SALUD = 'SALUD',
  BIOMETRICO = 'BIOMETRICO',
  GENETICO = 'GENETICO',
  IDEOLOGIA = 'IDEOLOGIA',
  RELIGION = 'RELIGION',
  ORIENTACION_SEXUAL = 'ORIENTACION_SEXUAL',
  ETNIA = 'ETNIA'
}

// src/personal-data/enums/tipo-arco.enum.ts
export enum TipoArco {
  ACCESO = 'ACCESO',
  RECTIFICACION = 'RECTIFICACION',
  CANCELACION = 'CANCELACION',
  OPOSICION = 'OPOSICION'
}

  
export enum EstadoARCO {
    PENDIENTE = "PENDIENTE",
    COMPLETADO = "COMPLETADO",
    RECHAZADO = "RECHAZADO"
  }

  
