export enum BaseLegal {
    CONSENTIMIENTO = "CONSENTIMIENTO",
    CONTRATO = "CONTRATO",
    INTERES_PUBLICO = "INTERES_PUBLICO",
    OBLIGACION_LEGAL = "OBLIGACION_LEGAL"
};

export enum CategoriaData {
    GENERAL = "GENERAL",
    SALUD = "SALUD",
    BIOMETRICOS = "BIOMETRICOS",
    MENORES = "MENORES",
    JUDICIAL = "JUDICIAL"
};

export enum TipoARCO {
    ACCESO = "ACCESO",
    RECTIFICACION = "RECTIFICACION",
    CANCELACION = "CANCELACION",
    OPOSICION = "OPOSICION"
  }
  
export enum EstadoARCO {
    PENDIENTE = "PENDIENTE",
    COMPLETADO = "COMPLETADO",
    RECHAZADO = "RECHAZADO"
  }

  