export enum BaseLegal {
    CONSENTIMIENTO = "CONSENTIMIENTO",
    CONTRATO = "CONTRATO",
    INTERES_PUBLICO = "INTERES_PUBLICO",
    OBLIGACION_LEGAL = "OBLIGACION_LEGAL"
};

export enum CategoriaData {
    GENERAL = "GENERAL",
    SALUD = "SALUD",
    BIOMETRICOS = "BIOMETRICOS",
    MENORES = "MENORES",
    JUDICIAL = "JUDICIAL"
};

